
# explorer config
beaconlight_beaconapi_endpoint: "http://beacon:{{ ethereum_node_cl_ports_http_beacon }}"
beaconlight_chain_name: ""
beaconlight_chain_displayname: ""
beaconlight_chain_config: "/config/genesis.yml"
beaconlight_chain_genesistime: 0
beaconlight_frontend_title: "Beaconchain Light"
beaconlight_frontend_subtitle: "{{ ethereum_network_name }}"
beaconlight_frontend_ethexplorer: ""
beaconlight_frontend_validatornames: ""
beaconlight_frontend_validatornames_inventory: "https://config.{{ network_subdomain }}/api/v1/nodes/validator-ranges"

#beaconlight_url: "beaconlight.{{ network_subdomain }}"
beaconlight_url: "beaconlight-dev8.pk910.de"

beaconlight_container_image: pk910/light-beaconchain-explorer:unstable
beaconlight_container_env:
  VIRTUAL_HOST: "{{ beaconlight_url }}"
  VIRTUAL_PORT: "8080"
  LETSENCRYPT_HOST: "{{ beaconlight_url }}"
beaconlight_extra_config_files:
  genesis.yml: |
    {{ lookup('ansible.builtin.file', '../network-configs/devnet-8/config.yaml') }}
