secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:fntl4mWciQgaQzELFE2BvS9ZGxQcJw==,iv:0tdxzEKA8SNJoB6JYInA6smdtWlyT1AsPV8cZTRuRR4=,tag:R3hsq117eDe3yINvGOPCLw==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:Q+c39xzsv8f1sc9wlRNLGXetJewRcb1zV20TJ4Zlx+C/IcUtw6oShPCLt0K/lg6bQecNn+8h9aaZaZ9vICEtytAPe/F9ygy3LuLqZtxF9fLPuDjqrHc=,iv:c828LApis2giEmlO5C1lFBqQBuZRTjuM3B0gWhCvgOc=,tag:1U7aLvRqEpxlpcfuSzWbaA==,type:str]
secret_prometheus_remote_write:
    username: ENC[AES256_GCM,data:b4eGJwF5CZUYmYgOtwZMug==,iv:aGs8i0K0rwM7J4Oyux6ty20IeEWN08gRr3hrKZwuY00=,tag:XlxBriyFLijFtFymh0qhqQ==,type:str]
    password: ENC[AES256_GCM,data:a+yn7XbpupEMwc5LYUBC++ljnKe+gs0tUgjuxX8=,iv:vGBvd5QyH4HrOAGBRoB/v6aZYPTiHVaMFfoRZj4FX9w=,tag:l84IDIYRLgJkT59c9kR8Xw==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:sc9ffC3rWvmV2KUx0M9gmedaKwaWU+FHZwAGVwFmqJMy/F/btB9HEg0JHe0soz46sCHOfyo=,iv:1BfxsNQKTWtUP6xQQm9IU+610bLO65f8uH8qsBSQNbE=,tag:ihasAJuf9sX91b3pOJOpwg==,type:str]
    username: ENC[AES256_GCM,data:7M7twmPoASyEolwvv3hVKw==,iv:QTYRXBkg5B/YXB1KEPPRrRUu716Z1Sw/DdZjesMd1RY=,tag:yqn2puR60CkfD5uIiF8ZoQ==,type:str]
    password: ENC[AES256_GCM,data:yvL5XEcOhuN59raPLYqb0CasR53aiCvi8+SuEbc=,iv:twJEJvlwC3Y7qt5YGw2iK2rwwUTwpE6B1BS5BteiSk0=,tag:DULvQKhOdAWhaW3IXtgaIg==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:ewHq,iv:3m9r+IutYQfVmmxnhGgrBTPf8AR5EY/7mxXSRscMgDo=,tag:9H/NPeIVAuDJ2W3L3sjIng==,type:str]
    password: ENC[AES256_GCM,data:GiqfFP7amT/6x3W75fMV,iv:H8CmQRbYnZo8zA4X3bK5/wUvWIDsV3MYRktaiLP0+3w=,tag:y+hEypeHIbXadljRAXGjtw==,type:str]
secret_ethstats: ENC[AES256_GCM,data:wWQ+aNQeF+gJk9ax9qEv9ZOC,iv:ICss4zaQ6umpIA5bQh1mToTFTd4Nh09Jr4W0RjDWmxs=,tag:wW131sx3z9FbQ4ABI9aIQQ==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:9oDUuFvBtjwRhIPOZAn6qe1O7kPR5XpUz+vi+ndbKlBAzoO8L66Jr1RVjuahjfzpdbhvdO0ltVcMYYAPODi0SfUzwwdiDGye6FQ7ljj8WbTPaSbL/qbEb0bH2c9Wj7SnapSodueqcEZk5PZYdIAvhX3wvMkldy1rZeaFvS7H3t0afWDUI5VuycoSCrFzbBvLqmGDN2NMewQc1EYT6859LxmDrWQ5,iv:OOvKVRW71zs+Y059eQ6cP7L5nckgNdVCOGAV+U+V4aA=,tag:+8OIu/w/imKxa/dC3gNacA==,type:str]
secret_xatu_sentry:
    server_address: ENC[AES256_GCM,data:Fk1yqdcZL9q2jvzeQh527uZpcC5KYZ2cMP7/GlcU,iv:0g3IXB1DutIJFGTq23/Kz24r3MwMiCPKbE4U68bNLKg=,tag:bFvg91K+M7gRNoJEu6/CLg==,type:str]
    user: ENC[AES256_GCM,data:CP+oFlU3+Q==,iv:rZI0Uy9cSl1x83Ev00I8iu51vQ7tEw97R1ptAsHcJj4=,tag:OUmnkc1PXD8L5NA7043ZwQ==,type:str]
    password: ENC[AES256_GCM,data:MPiGyB7L6aJ0WmI0AZbsHntbMh1wROoQ8ek8iwELDHZTo3AI,iv:jg3K8YiaRIUopk4A3Kq5XUrzjWezto4wcmRCuLKoBrg=,tag:WswN/DtPEEVt82Mupf7sQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hcthyar6ujws8nmycmvh46f4luptqdxgf90z2a3ducedwmfvzedq7veutp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdDJSNWJ0WXBKMStXNVRE
            L2JLUFplK3NHZmdneGxicmlzb2lscHVHNW4wCmwxRlI0RWpydmtvbHFoYkkxNXE5
            NUEyZkhidW9NNUgvTFNFOGVWL1hwN0EKLS0tIGJuUmE4cjRrclU5UHUzK2tYMG45
            SEhZdjRsN1BqQVlpTHIzR2NqMWg1ZVkKcufbKcr/+hixYLOgzZ8BV1HJbGCFqvKt
            YRhu1udumRJUhb8xgD/WVJ7CKaxn41FfwtJmD1di0FrPs77UPOgr6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T12:44:23Z"
    mac: ENC[AES256_GCM,data:57JthVyT8eki9GWowsxTmioM9CPYNySvxj4H0OsqM1ZM6XRFYH+zbCdGn4dekjYG7MFsxVPb2ChiWfH/0He1xO8KNvv+zQCefo+ZH6zGiGeCGS3aXm2OVy39sC4cQOqHV0ThtDQvpltyuZvoGbVtGpMl4UKpbj3j7ElkuRQkuOM=,iv:1yI+NAGKSlKpoEOSq41XJSoDk78W+7oTnAA5CtbY1pY=,tag:hgyzAtBp4S1ZeRcI+BmSjA==,type:str]
    pgp:
        - created_at: "2023-08-17T08:39:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA32GcoRiZf6pAQ//VKseo4KQojyHdLzZkA+K9m9WlZgT0KTskcLWM2nOI8iS
            kUn5jl2yJgUtST6x/OM6E6d3kmaBVe2gZDXt7IpdOVxa2oeBTgYOxrvkVyFrGZrW
            i8QhHqo0GXniRF2K2JRCR36yoLIrPMbbfqUw0sViXmnJVi2oEvNDAI3JRssh/Sko
            bQBeyeSV5NW/7d4qFXGr8cMbk30rftQb4WBSeCGs6Th6OYL+fXQImFcOaCtmbD3b
            NCvM6Dlej8gEFGHzyc3BllsapLDDDa0bJfPztIXYgd3ulKXk6MIs065Npq0Bb70D
            PM4/FxlNkUp6IjmApRZ8B4N+VZFtNOrteM8c9XcMw1gmkvPCV0qZHdgWpX9CrYfL
            Dw+gpvJkuDG5baGsbcfM1FqcYeDqYWS02xy7WBYNhjuckxtGbWQEDkxJfR5EfHmV
            xsui3f6A/29XIRPd+UIOEOyAeSuANPnbBzQuiZM4NnU13pXIFaZYrto1m7dffv0v
            qab4H9NXZG020KkGE8rdMFxwROKjG+u1OtjZ3v8gQhVUaVAC6mU9OEEv8ceLbtwq
            c1uICWq+TT+vTQVerDypfcepeDbCqNdL9tMkfY8UEkp4PfLOxODPeWV6kfX2Jdbl
            Rp5iLRTE0OkLuVrjRGW0fF6iVz29BKMU6PD0mnkeXO4q/Y0lOiso35g/zyYP1jnS
            UQHHEIShnm6LrtaRAXh3fJWv9bdNBrzKx4NqRwxtUoFFoMwe6lM0OMuB/v6aWgWr
            9GUZbYSdPYSq4o8FfeOOsNawoKsQF/sE0Xt/hYh0YP5Hnw==
            =unmr
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2023-08-17T08:39:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA87Wber4r4dGARAAjoI/b2siL9PZyxyQBwaQvAjfuq+KWvOMy1vkdD0a9iqQ
            88n2/fLFLtU9IwvOtjf9rVayS98ezk8zX4k0avv+2UXzkEc7//gnHOkwYZWWCitK
            y2KhZSAyt9xGUW55AZdReEF9DDLMH9u7+S5TVILPgwsG2kV5Z8Pt0sxEnszf4Lw/
            CKq7Y5B3/4Nn6Um0gRDgK+Rb0I4d0bJ3oo1DduiPXU6QpYOKA+mkhTRS5+WCVtK7
            spEvuniNXNLO/LAdsj/KmYHHXuE91eMTWbiOnSxkvqd2q96U68udqKQGYFKhChi+
            E44tTgzPoa6AtzHuMN9S/M7tT0/ctLmFp2GUtsbQ6VyOVVRWMYxCuxJSBwgXVsQW
            lgc3Ae67NZi9PjPZQxVYS3JVSofbuYlU8s57jFg1XwHmVisWleKBKH8DLEOymvju
            4wcT3pUQ2OVytHxnRGphFvofHCM7URd5pgkE81uqYbV2gWCa19UmD2L5lUWtPLaI
            qIN0X7souwN5zc4CUN54sAziPEL29Ip6c3DWtUYz39mIne9LDuUQod6I5XO+4HNh
            1ZgWB/OWvFPCXtFAGVW7mr7DvsglPdFKg1MjE681UmdX4XWps1/fzYEPtZwXUAh7
            ocM6RLd373UqlfWX9UZtoRPsfy02O+upObuB+IPVU27qTgYnPkdftdKEluoK6e3S
            UQFCtHimrs6EFUMYsxKOBrnaDKA/bNBiqNsxlPBeG5jnLp1JaDFbCUd46HOcs1Tb
            aO2UI9hvCrNOArIABog2UCJvvhAT5HYd7S0ODBuQLLdD5w==
            =EpQM
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2023-08-17T08:39:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyAQ//T9T8JI8SLQGm9n/VDGrNWxeB3QOy/96ssisWkbD2ZHTR
            Ubqi//Mrmm7fllnWpOL8yP+UqfxkZNDSfkM0v4DkLi5+/7WHRfWvcUi+bLr7tQxz
            ZYHPBP8lJvGE/u9Ws+Rryv3XdSvnnJw4KpMS25RRWPc2lVVhl1IdXWi2+O8ftza9
            4C6iclXJ2qNOwbrco3UTFGJudQu7eu4AjoVI16nOm2OsYme9kiDgLD+aTO5ggv49
            RSexAbrskQdvYpLSg3tgXKwWyOd6rN4Y00RkmNZxaU4nVdO62WrxjnwvuzSMbDZ4
            eThBDzJi/kTNtKQdzEJ5gOP4Z5dEAKVlu+usCBnqRX6gIQPag6e8WvWwU8w0pIQX
            FNuz2OTr1UHKsmD9mAuup59mOdQXjM0TE3Rm3GT5DfAJ+0gMOwFSPSr9T5wrZJVe
            5kl4cdtJNi0cuuukd7OEgHIK2jtnuV1PzyNQiZo7mmEE8dsNl3a0ufBcxyjru5qq
            pSaqlML802cD95q0ShYrl4gqd/4VD9GzdLYWExX4DaHK5tIzBQOI1ZpiMax0hXyn
            r1aC/EYc4UupYJ0qzm4FV8QQGKpXCELCVjVEw6CQ6739TF21AY7+C/g2Vd72tozf
            R/w8cEi/thm+gfAjU9X2JXR5RkDdMje0oVElu4XfziCMCS3TVkiIE5BGGBeKknPS
            UQEtfay/t3IkInnP17idBnbP9gnaQZgE6XtDoGy6iwnJtqmv7ZNOpIZatWHYEuau
            +XV8aloLEUy08U5JalowqAZb+RYIFNFhjdGWOFDKfrPjDw==
            =nHck
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2023-08-17T08:39:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAw01qfIBwY0JAQ/+Ka7S6gIfQB5U9TC/m80kzfvjffG8/Ur1uodS1setwIQy
            u3FDqoRKOTy/1kh/vaUrJOTK2VQoesqD49SHt1ISDn/DRDVmYUQeaa23ZrDSukxB
            h++nU4LI30ZJ+PlRmzrw49XTvKHBQNm04NWb47dC4zeLS+G0/5ZrIsd8mcfCg82p
            LsCyjIwllCPcLujpPOT4FZh2kOt+zO9DWrv+5FJf44zNBn3ulFvEEH+csS5MPubK
            cQfHyPYONLW4l5WG7wrYttGMX82orE2V6tgLj0RA2sOQlKqYAykJMzgjS85IHWdj
            voz8NskFMboEC97SWBu//Sxj9Rh42scdu+tACMw9BwUSyI+EDZOV0xMkFpD1akNS
            rvzmBzaTwejp6FgPhrLf5MEzF+RUNUXMa6Jt2tUY/0Z9oR4ffbIhyx+sN18kvmL8
            njnoNnlnJJqyA+mUAPorMaeqy0m23QmsYGAPERAhWiRgCtJVoPYtMoG62GrBVMR7
            a5Tk49l9yovi82Fxgwx62u8C6+CTTX6jT0oM6gAyFDfydWHLG/cVy/9viWhNhtCf
            nU2WbyCaC1qonGF/Bo+GXUgbUMpOQFCDrObXSp+bbJ1StE9vXzuTCeHSsAyzqPUF
            /m6/p6INqMyS0LSu7LDmuIXkXS5FLcXSVGRKiDkfG0INDg8y+kHbANQmGfrsmh3S
            UQFk7PK6lQloG2LeinAn2sIK3Tt4qkCUlo90be8YnzkUWMTSOB1d2hZ5SQhQW1fN
            ae3I+AqHgxvYMhQrv7aiFYlq2dLon51oc8ts/2/WOpxHLw==
            =e5Xp
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2023-08-17T08:39:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMAwDFOgk9tOQ+AQf/TCyiIQFXZDs8FvXIZoYd1RijKLGddt9XORyykwPgU4WD
            1tESkYRJIidVTIBu8nSvU8Jfm34PGzgDkJtHAwMfNuAFKnwqbZPrS3rWamKGiy47
            fhdFHZzOMJqfuapcDDvmMvC76FrYhPP88EwEFOZSCmJD6O50pNbdrhN3Hbjidk0I
            wHeXTosOMF6RyT8kJhpvWSuWMl5/5fWSnEcKtfQvUVUt0dt3vzLlQqFRHAQEn4hV
            dMDsGBPkunCNGuFrCwNb/tGVY+RABtYalkxjpfxubFUZI384Vey+UZb6VVC0HY1f
            xHn1BMihX1i7VI7kpXYRXAEiRI8572D+lYS/0tvK7dJRATda5+jf0TOgFyd/90Lz
            YQhqfuThF9abN4nMIBiP2tMchA+b2AABgIBlgCiUTLpQswa8xofxNxmF8IvoeOll
            YUozT8aQVO8msAviqVhziUH9
            =BEhT
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2023-08-17T08:39:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ/+JmXYaQF8lXc3wQ4Nl0QK/QPfDTdn4QhZ2DquCA/5ruHs
            /Pt+QdREMjAkpYQ0n3QP03cJdxunoMOk4bhv8sE5Zw0bKZk9ilu68SKP+UlfpTZX
            MJk70GGCFv5PH72Gz3DK4Ed1AR92CeOUJG1HBVx2WbKAKVvL88zbapIkifK260j0
            haqAlSiEQxFO5SdYDZ6wv1vEJ3+D+Ujulby0B0HWRD9FTECLt2Zb/oX6vQNWYZwH
            4X03RRnwk0G0/9zfSS1j9tBK4g75NNixaHvgWywpzBudcnEq9uWWBMjbbWX48epm
            LzajdgVMIvs3pVO8aJlLuyr5Yu3lbJteBVQQffrBU7N+iLmPWh78kNEVE5AldNpI
            YZokzhAiN4StgqEY8kKaZlJeRxAWUHrZHwVfZS0r1dFz3q0v7COdmA2VWIAulFSE
            0sBrpFNSKnbRDEgI9rqJGJKTbdG4kvZejE+XzcaS92VDzWdl15uiynt7VRHbN4YU
            0VeBG8qDyTXcQomiAUu5ilcLgSIbejWkS9Vw+daHEYGC+Hl7t/GCSh3QJGURxc0S
            mzri4O2As6xVDgqMNEjQOZZAKi9cgROoKcSqpjpHma+xchu/kT4TCYIZpvpwiptm
            NvAZyaZCYvuEie/ix9ck3Qx6GelCFCIIRdi1r8vow0xWtpgOfbTatXuS/v15TfLS
            XgHxPJ/tj96j5+9xbsKrukeLKVznJEOIiycryPanZQbGAho9nwCT7K3EedlABulf
            AlWuUG4AVjh0Bcm21rB3IfcYk0SCkxS46R4SdC/3kQ5QTD+EQ2LtTSmE5RTCMHo=
            =90et
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2023-08-17T08:39:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DORxA7Ajr8awSAQdAJyVa3+1CUjqy7hVI3diWsxKLTrT++E6jAXtPLAPCKEIw
            5Ae7oqI5INAoeAwulKSy+7rXfGWPBX42FRFjWN9tPVdryjd54FmBo+AuIuMqddtM
            1GgBCQIQH3kpslp/Q8LGl2dpb0BDi2bIyAWQzkNQKE06zwKVtSt+5QbFKQ2+F6fS
            y37sJpgkYvOqBh1m0nRkl2U4f4Y9gNFspT5zTe0qZ+5cHszOgqW+eENf50wb9QFm
            17KNFi5EMAZJww==
            =YJLT
            -----END PGP MESSAGE-----
          fp: CEA1598FBCBAD929A56F24F21AE82838CB1EA4FB
    unencrypted_suffix: _unencrypted
    version: 3.7.3
