cl_bootnode_privkey: ENC[AES256_GCM,data:pngPM7PrcLgR0j4pfJcyTgew5JMFBQPIDaIDVIOxsVwC+xXZcRN/0DZtZ/9RqiUHzEOP+mFaeeIAepi4/YApOA==,iv:xGLBcBzZIEBDPSEfkdcicSja3gjP/y0rEiqmzUCSkt8=,tag:RVq9eQfgjHzzyxLQdfbYwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hcthyar6ujws8nmycmvh46f4luptqdxgf90z2a3ducedwmfvzedq7veutp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU2lSU1Z2NEJxUzc1WFp5
            NGNtazROOHlkcm1JbEttbkFIcG96NEhQOUFrCmdvVnU0K1hiSy9GR3hkSmpDT3hB
            aUtheEY3MjgxalFPbDB2cUtyc2dMaFEKLS0tIFhSb2d1RkdrOUc0MitNWVFSVjQ2
            WDlDSTJHMGg4UUFLTmh3NVdmNEdCdm8KckqUhtxTSVrOW164JbC4U85QGl/+sBuC
            U5m5XbPXl75+CQ/3gMhUumpN89CvsoBLKmd366kyOoCUK0QLvzplGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-25T08:52:48Z"
    mac: ENC[AES256_GCM,data:P4+USYovks77A8OoZ7Daxt2ayRUPV3An619SArwwc89BjYLVAJDf06WTU7LSXMJG6uBunQoOohk+6Do2Jl8tFW21lkPW+PQOj2K8AU3ErlMutyakSWqiYQf5pgKL3hLYCcod4haqVcj47JZNOs8HOgu35UPaIzAPg+uXGUmka2k=,iv:iFwuTj9mV5e7fX9jWhyiGuFmNPjsqPOb1T6HUtpr4m8=,tag:W6eyVCUIQpQcq++LcFqahg==,type:str]
    pgp:
        - created_at: "2023-08-17T08:39:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA32GcoRiZf6pAQ//WehBIiqqYoZqUqIehUX20KEfDv96xvjraGUxHEmfdxWB
            XUDpT7D2StFYKpktlJESAXXqFc2eBEaIChbk7rROkj1egX6vw3mIqiOoVYpSBPlT
            kVGB02eIdYnUuQJNFyW2bOu4MHWbT5sWLkDTNphIKAEjnuBI29p2vuJdiPvz62yt
            LKBhrlSE3K6sLWn+jj+UfQfW7xmi8wRK7vkGMZfOdxEr7YwrIDpeUgM5J6w/TqY3
            n4WXmQfFTY/P+0YIB6U9f5VK9P4psRBW7VLjC3sxjZH2H8yTDEc3tr+kViRN6WF8
            lhB4Ix7erlB2o7ufmsmCaH5fhfCvBU98dCkg3dx2RwO8TXKjMKhI8C9EGvPQsP2e
            AZEaGissd4CZxXa7oCjIS16ZOKa78hRGX27aWNLfn8mhFejoPUwfP+g5eOAiReQ0
            bmczI7o2afIta10aGz83OKGSqS1lCPoyWzNFbH4xV7+TOMQTgz1sZTVPQKBIwwvG
            G67y+taDSpZeh9Psqmt3Oy+acr3ISFp0v/xCB4xcixabMt2FTZdTjfZKveT+kVWD
            aVl5nzemFDES4q1qBuBk9dxdifoFOo6l095drhuniJC+tR/KZKrWWPGR7FAvGQcD
            8j0RDXifl7RSTkyYKBL4sEkmr8gnDPiBOLv9PJ69zytia4EpuiAoI58iCgDkSYfS
            UQGYljh70F0DoGElLwgNsmVv/eTyndiVahmJk2ExsIzwvfomG1UIPYvNGaLgnEb4
            ZuT75hGLenIEo/B6eGxHdDhqH9WG2F2G2UmbbNhKu5/4AA==
            =OVuU
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2023-08-17T08:39:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA87Wber4r4dGAQ//RCJPSpyaqxy6nqxoOX2sPgg1T4BtNeecOQJO5pvTAFOw
            mD5n6YNKDrVhDBT6/483E3EIOpFzeu+brR1stSe0dSf2rN5fO5TNx4jUlv6dLLyY
            v3sbi8XpWbvh/i5LAQQ1T+aYsWij1Jxml+aRMuK4CoCzfi83dX4oIeUMihsVgfOh
            W40UzbbI2d9CRiZ5hrSVEyLJlGSZFKBkWbcpzkdZwSeo824WhOBbV22de29xo8g7
            KJB9yMHGj9w13kH5rMnV0Ry+GXSKAnTlWjX9UUg8fwvNo6WatmCZ/zlN1s/v641X
            l/26dLDxb8jmeCmSCN7OlXkAXW0+FJOEebDcO6wCk9maOBmdToYGhT+tnvUaXUjE
            Z1BTkGl4EbfVY1y4o0V5Rno+NYxK20LsYPDRbiVQ3n0k3K2s5/WebsQ+alELEcvS
            adKr3nYhf3nT2KfVBR+RL/VEHY/zigeMuX9VK13UtTy/2/HFVgOiHoM8krxxq7qq
            gB80yBGqKxSoGUh6SE97CVZyu5PyHo1rku0v1tSh7nBGfq0HWS8Toh9qaZTRVoqj
            6OlAiqICXmJdb1a5ZQf9C9FOmSVedXnN/c0PfCTGcshdAxlfI5JWEbJuAn7mG8Yw
            lhS2W+xJJ0QR1kFIXax8qwxjEDTNprI+a6sDzXyyX7dzySfpKm7KcYvySRs0hjbS
            UQF7oaS7CxejGKg0w3eh4jQilkkTyjYM937nZzU11VDzjAmEu2oUiKRMahkXP0lM
            4HEL9ECw9cGmKxpGt4EfHf12XmIwvRkTh4CTfiOwUkKvUw==
            =JsOo
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2023-08-17T08:39:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyARAAnaJEX1LoqI/tqFMg2koyvMMlGyF9dVc2q7HmbusWwoc5
            5YaTyl/n5Xn5riRRQSOLkPfMHeeoFZBEMtrXVFDVHaVaJNePZmYeocUV6ypdkmDT
            5rN98f+mvsGaHv7/1gOCd/qaz0jC092MyKZDRRgimjbvgPTGYbnUUkPRHC9ltkDY
            4xqfUUldZPQRFo5dPJM/Bf0dqkaBUfuOTOdOmuFMbpHB8ycQzLkpr+/YCxtGPaPW
            G2v+I2dHRhnDt42QuwUsFQOKoeDsm2y+ZLMG8FjbFet+/+F9J0XJ/Nx1HYAtSXHu
            NQmU0h563b4VBLLV6m7+A19cZqHYZnZpxAzHq69WyoiEM3kxhnvfVraxgo2gHYSf
            7WduAvysKgtEgp0Qto0EDsLAdsx1TQP6eZOtajb0Fxc6dQSbEfh/6nlrz8xJzHb2
            jm0kC06QbU0lcKk/Rht+DG8EugkrGkJuTL/X+WENEjEwienzBZ7GPU+NPq08QzVh
            yIW+NspDa8CevdwHyAXhU98vTodFw8h1sqzmHvfuuFV/d9buRjE68UvtFVHTWvXf
            14OhtuOplTuy6mC/2vLkxaPbnJXplJuvimMWZteYzcepIZLz19cFBLyz8Iq2f90m
            V5PJgEfsfisAmwpZ4801dJqS7qPaiGUw15o9S/JfA7U0NvdF4P2rXZIrGnt6bJnS
            UQGSBUSENsgSIU27S4Y2p1JMQtrFw1GJjE8SHcoJxySyx4N1QgswwWOnwR6PPMH8
            EKIX7BSnlzeIslYc23QqwT2+rrCAld/b6H4ROg1McwHRvg==
            =czef
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2023-08-17T08:39:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAw01qfIBwY0JARAAuc982hZQwFyck3wXt/SBJZCCh9f2MUxvK6gnUz5sZtV2
            5M8m5+hq1XpPkJhQshpOEQcU8kLPEy33AmA/SfO0Pm9WywyPjmutcZqEVIYk9oiw
            QzifRfH28i9uQeHmBkChM7rfveIX7OkbnvwmxQV9TA9f2CmT2m5paEHLFv4e2swr
            3f7fzftyzAjqKKRYkxLTeMekba/QVFIag33i8uDRT9TzEZNlLbviVa+dgo8Vwn7H
            VCPHlcenuFHic4oN3JIL00uMg57OcwAL0fJ2lZmJPQf5AYSQJJIBMADle6OjyjiS
            lf9G5RNCWQLCNlrIL3IJ/gAW7MQ3vwosKHn/UBEFI7ZZNuCL8OAHE5bpWSYKgpjP
            tpGCJnU39CLUJ55LRdtggh89rxmmM6Co97o+hWKFBU+Gu4yMcRtUDtT2sFrSMLgT
            Rz3zvHPAp+BbFZHD5+DQngUG0tEXAO+ZKKHe4wPzVgkb6kMaKzBeFnD9zKcdrkPf
            hkvZNF8r/KPP5KpVbyHtVaCqCWrCCBYD2cp4tuBD/XOsZw8pVbnJiduYeATUDU66
            Yx97LoxZy1smufRd9fH8gkulc/X78D5i0ynxv1ylDN8+Vy3oS4k7IAMSrNRhPr9i
            PZz9thNie8k9recwNuuir3hURYbcLAtGZE0pIoGG1dDOdReZJMLqPgTdvG25sO/S
            UQFr+LxoCFT06bbJxMPKKvAVFO4i+kJ+l76vRl5LWePRXA1/IDozYpkR3dmlk5/g
            sRXH0X1EEY+OtyS8kIMRwOJ5C9mTXGYPEUdg+cluwsA0JQ==
            =4yFq
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2023-08-17T08:39:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMAwDFOgk9tOQ+AQf9EXr7jShYdqhcOOLzWM7mJj4DUUFi50VBI2WCDi+sFXlF
            cGF17oA1xbZAXPYdn8iAsU0hVfpchFPgROkKvhjrRKB3AEGIcfyT2+haLkoVjbM4
            L5ng2GQ01VUeqB0Tn+RJ+Goee+/nbBguhIMZdnuUnhJ0B/ARsAsTW5ISb38Fm400
            XcYYq9bETHDb6WuLPNl/Nlehb2sG0Qq8ctjcY5ImBkDSWM13yrt0S1eRLTJChTT/
            lTnfFcrSbI/yrlaUPmjVsrFAyAMTAbgStpK1hVwcGQJRCLY/TApjNjFo821jlduB
            rmiJh+Vqyf3Rd5qLGmJf8JNcVtjZBjfsF8Eh3aYb8tJRAYUTF+1ihqqMtW271GKs
            yX8VjVaBXmK+/cuyEQZI9AEVss+ksCORq/gNA5Rs+ypkBUwE37VOMfRC+TrNMfYL
            wuv/6xVR/II3xdwMxNYuzcnJ
            =sWSP
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2023-08-17T08:39:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ//fVVgX/YiUON0u1UURCeBhy1EmoSFdoS3YJ+SeXESKnyZ
            XynvlZLEVV4CVahZy/ov9JAV+bVkJbkJM+cc4UHuWsG6fk0sQwZKCNhIbTbGvFrU
            yoK7Dhk+oi9tTz0hCeh9VSoHidivXSKYvTQ9CFd400f/9YZfSUlnFoVJvnDKTpx4
            TMYqbXEjMvqFF+Fv9A+wkIJJEjVfbciX8mFIYnWlIy98zM9eeaFGJyRTX2gDBbaI
            J+Lhi5WWOPRkiZaLXC/KZFZ0JePGXsHcCeUcMv3Td3gkMoY20v3nyW8gd766Rkmk
            7hHGYpF/VX95Fuau60q32RPOzVC/CU9POUWeAW03jNPjS/f6jigWRwNCzTBto1JK
            6a6mJuOJVMOWgmeJihr/OROhynMH1Pfw0NjE6+CVd7/I/TX1plEWWSoDzLiFVjv3
            c03KJP/t63oBlNnRUEKDPY53yxd3fEcb4H0ASF/JaOEsl2wKOXrJCSM+H2899IhE
            LsRjKsep9uy0UD0Uv5vOWHbwyIH+K7mC2mjWcDx9dMEcvvqFwodGoyg50alkq33H
            Aejs7XIplBrPhN0LbcfBvoCe7/y0XQp5JgF/CDfjfNE8SKZE51PNa4y045r6p26a
            NlNn4tfp62U5HQ4p8Q46Hnn6d+VnNZxnWp6XhAPHhmzs6jl7Q45KR5sYK7e/MGDS
            XgG37mJ6wlSstxGevJMbBf0Xm1/gtTwjObQTpM8pQeSmPeqmeTrzPA1G90g530yK
            NW77hRSzwwyLMdx15Fon7e/+EosPqFql+3xNlyoA4EtcCXIRt9Fu5FgHz5TNHhg=
            =ISpH
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2023-08-17T08:39:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DORxA7Ajr8awSAQdA+GcBQmZw7XQgfjR6JpwOaH8fEwsEkivJehEGDkkV5i0w
            TDceDOjOXZdMHrA3vxjKvETExIIPc20Y/GccM9iGurN/Z9DgjSWXUjtqTVPduBlA
            1GgBCQIQplQFoMu+BqmWzcQ4TLMuNvAvwniFN/QJiuW5XHvmVaRnzk05kCTPZ4YI
            cYzTeLHiJ00oGNAjsD/8Gz7vKz+2RFOqPkEQetFChpqWFbH1jJiFbmXcO8K+p9hy
            9Q4xl2T4Fd8vNQ==
            =kzWl
            -----END PGP MESSAGE-----
          fp: CEA1598FBCBAD929A56F24F21AE82838CB1EA4FB
    unencrypted_suffix: _unencrypted
    version: 3.7.3
