- hosts: localhost
  roles:
    - role: ethpandaops.general.ethereum_genesis
      tags: [ethereum_genesis]

- import_playbook: ethpandaops.general.bootstrap_server
  vars:
    target: "all:!localhost"
  tags: [init-server, bootstrap]

- hosts: all:!localhost
  serial: "{{ batch_count | default('100%') }}"
  become: true
  roles:
    # - role: robertdebock.fail2ban
    #   tags: [init-server, fail2ban]
    - role: geerlingguy.docker
      tags: [init-server, docker]
    - role: geerlingguy.pip
      pip_install_packages:
        - name: docker
        - name: docker-compose
      tags: [init-server, pip]
    - role: ethpandaops.general.docker_cleanup
      tags: [init-server, docker_cleanup]
    - role: ethpandaops.general.docker_network
      tags: [init-server, docker_network]
    - role: ethpandaops.general.node_exporter
      tags: [init-server, node_exporter]
    - role: ethpandaops.general.prometheus
      tags: [init-server, prometheus]
    - role: ethpandaops.general.vector
      tags: [init-server, vector]

- hosts: bootnode
  become: true
  roles:
    - role: ethpandaops.general.cl_bootnode
      tags: [cl_bootnode]
    - role: eth_testnet_config
      tags: [ethereum, eth_testnet_config]
    - role: ethpandaops.general.ethereum_node
      tags: [ethereum, ethereum_node]
    - role: ethpandaops.general.docker_nginx_proxy
      tags: [docker_nginx_proxy]
    - role: gen_basic_auth_nginx
      tags: [docker_nginx_proxy]

- hosts: ethereum_node
  serial: "{{ batch_count | default('100%') }}"
  become: true
  roles:
    - role: eth_testnet_config
      tags: [ethereum, eth_testnet_config]
    - role: validator_keys
      when: ethereum_node_cl_validator_enabled == true
      tags: [ethereum, validator_keys]
    - role: ethpandaops.general.ethereum_node
      tags: [ethereum, ethereum_node]
    - role: ethpandaops.general.docker_nginx_proxy
      tags: [docker_nginx_proxy]
    - role: gen_basic_auth_nginx
      tags: [docker_nginx_proxy]
  post_tasks:
    - name: Wait between runs
      tags: [ethereum, ethereum_node]
      ansible.builtin.pause:
        seconds: >-
          {{
            batch_count is defined | ternary(
                (batch_wait_seconds | default(30)),
                0
              )
          }}

- hosts: teku
  serial:
    - "{{ batch_count | default('100%') }}"
  become: true
  tasks:
    - name: Toggle log level for blobs
      tags: [teku_logs]
      ansible.builtin.uri:
        url: http://localhost:5052/teku/v1/admin/log_level
        method: PUT
        status_code: [200, 204]
        headers:
          accept: /
          Content-Type: application/json
        body_format: json
        body:
          level: "TRACE"
          log_filter:
            - "tech.pegasys.teku.statetransition.forkchoice.ForkChoiceBlobSidecarsAvailabilityChecker"
            - "tech.pegasys.teku.statetransition.forkchoice.ForkChoice"
            - "tech.pegasys.teku.statetransition.blobs"


- hosts: bootnode
  become: true
  roles:
    - role: eth_inventory_web
      tags: [eth_inventory_web]

# - hosts: beaconchain_explorer
#   become: true
#   roles:
#     - role: ethpandaops.general.beaconchain_explorer_aio
#       tags: [beaconchain_explorer]
#
- hosts: beaconlight_explorer
  become: true
  roles:
    - role: ethpandaops.general.beaconlight_explorer
      tags: [beaconlight_explorer]

# - hosts: tx_fuzz
#   become: true
#   roles:
#     - role: ethpandaops.general.tx_fuzz
#       tags: [tx_fuzz]

- hosts: localhost
  roles:
    #- role: eth_post_network_setup
    #  tags: [eth_post_network_setup]
    #- role: gen_kubernetes_config
    #  tags: [gen_kubernetes_config]
